config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'
  resources :users
  resources :sources
  resource :sessions

  get 'login' => 'sessions#new'
  post '/' => 'sessions#create'
  get '/logout' => 'sesssions#destroy'
  delete '/logout' => 'sessions#destroy'

end

app/models/source.rb
class Source < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :link, :category, :description, :tags 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :sources

  validates :username, :email, :password, :password_confirmation, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end
  # def logged_in?
  #   current_user != nil
  # end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:username]).try(:authenticate, params[:password])
    if @user
      session[:user_id] = @user.id
      flash[:success] = "just a string"
      redirect_to @user
    else
      redirect_to root_path
      flash[:success] = "just a string"
    end
  end

  def destroy
      session[:user_id] = nil
      redirect_to root_path
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: [:show, :edit, :update, :destroy,]


  def new
    @source = Source.new
  end

  def create
      @source = Source.new(source_params)
      @source.user_id = current_user.id
      if @source.save
        redirect_to sources_path
      else
        redirect_to new_source_path
      end

  end

  def edit
  end

  def show
    @tags=@source.tags.split(', ')
  end

  def update
    if @source.update(source_params)
      redirect_to sources_path
    else
      redirect_to edit_source_path
    end
  end

  def destroy
    @source.destroy
    redirect_to sources_path
  end


  def index
    @sources = Source.all
  end

  private

  def set_source
    @source = Source.find(params[:id])
  end

  def source_params
    params.require(:source).permit(:link, :category, :tags, :description, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to sources_path
    else
      redirect_to :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wynsources</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <%= current_user.username %>
    <%= link_to "Logout", logout_path, method: "delete" %>
  <% else %>
    <%= link_to "Sign Up", new_user_path %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/sources/_form.html.erb
<%= form_for(@source) do |f| %>
  <% if @source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@source.errors.count, "error") %> prohibited this startup from being saved:</h2>

      <ul>
      <% @source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.text_field :link, :placeholder => 'Link' %>
  </div>
  <div class="field">
    <%= f.select :category, options_for_select([["Select One", ""],"Testing","Ruby", "Ruby on Rails",
        "Javascript", "Jquery", "HTML", "CSS", "Agile", "Lean", "Git", "Command Line", "PHP", "Databases"]),
        class: "field_box", placeholder: "club selector"%>
  </div>
  <div class="field">
    <%= f.text_area :description, :placeholder => 'Description (optional)' %>
  </div>
  <div class="field">
    <%= f.text_field :tags, :placeholder => 'Tags' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sources/edit.html.erb
<h2>Edit your Source</h2>

<%= render 'form' %>

app/views/sources/index.html.erb
<h1>Sources</h1>

  <tbody>
    <% @sources.each do |source| %>
      <ul>
        <li><%= link_to source.link, source %></li>
        <% if source.description %>
          <li><%= source.description %></li>
        <% end %>
        <li><%= source.category %></li>
        <li><%= source.tags %></li>
        <li> found by: <%= link_to source.user.username, user_path(source.user) %></li>
        <% if source.user_id == current_user.id %>
          <li><%= link_to 'Edit', edit_source_path(source) %> |
          <%= link_to 'Destroy', source, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        <% end %>
      </ul>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Source', new_source_path %>

app/views/sources/new.html.erb
<h2>Add a new Resource!</h2>

<%= render 'form' %>

app/views/sources/show.html.erb
<h1>Sources#show</h1>
<p>Find me in app/views/sources/show.html.erb</p>
<% @tags.each do |tag| %>
  <p>#<%= tag %><p>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
    <br>
  </p>
  <p>
    <%= f.label :admin %><br>
    <%= f.check_box :admin %>
    <br>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %> 

app/views/users/show.html.erb
<h1>HI HELLO <%= current_user.username %> </h1>